@echo off

echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
echo Grab ur water bottle
pause